[package]
name = "googleplay-scraper-rs"
version = "0.1.0"
edition = "2024"
description = "A crate for google play data scraper"
license = "MIT"
repository = "https://github.com/eoqci/googleplay-scraper-rs"
readme = "README.md"
keywords = ["google-play-scraper", "google-play"]

[dependencies]
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
regex = "1.10"
